#!/usr/bin/env tcsh

#
# Copyright (c) 2015 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

set packetdrill = packetdrill
set delay = 1
set testcases = (sctp-idata-01 \
                 sctp-idata-02 \
                 sctp-idata-03 \
                 sctp-idata-04 \
                 sctp-idata-05 \
                 sctp-idata-06 \
                 sctp-idata-07 \
                 sctp-idata-08 \
                 sctp-idata-09 \
                 sctp-idata-10 \
                 sctp-idata-11 \
                 sctp-idata-12 \
                 sctp-idata-13 \
                 sctp-idata-14 \
                 sctp-idata-15 \
                 sctp-idata-16 \
                 sctp-idata-17 \
                 sctp-idata-18 \
                 sctp-idata-19 \
                 sctp-idata-20 \
                 sctp-idata-21 \
                 sctp-idata-22 \
                 sctp-idata-23 \
                 sctp-idata-24 \
                 sctp-idata-25 \
                 sctp-idata-26 \
                 sctp-idata-27 \
                 sctp-idata-28 \
                 sctp-idata-29 \
                 sctp-idata-30 \
                 sctp-idata-31 \
                 sctp-idata-32 \
                 sctp-idata-33 \
                 sctp-idata-34 \
                 sctp-idata-35 \
                 sctp-idata-36 \
                 sctp-idata-37 \
                 sctp-idata-38 \
                 sctp-idata-39 \
                 sctp-idata-40 \
                 sctp-idata-41 \
                 sctp-idata-42 \
                 sctp-idata-43 \
                 sctp-idata-44 \
                 sctp-idata-45 \
                 sctp-idata-46 \
                 sctp-idata-47 \
                 sctp-idata-48 \
                 sctp-idata-49 \
                 sctp-idata-50 \
                 sctp-idata-51 \
                 sctp-idata-52 \
                 sctp-idata-53 \
                 sctp-idata-54 \
                 sctp-idata-55 \
                 sctp-idata-56 \
                 sctp-idata-57 \
                 sctp-idata-58 \
                 sctp-idata-59 \
                 sctp-idata-60 \
                 sctp-idata-61 \
                 sctp-idata-62 \
                 sctp-idata-63 \
                 sctp-idata-64 \
                 sctp-idata-65 \
                 sctp-idata-66 \
                 sctp-idata-67 \
                 sctp-idata-68 \
                 sctp-idata-69 \
                 sctp-idata-70 \
                 sctp-idata-71 \
                 sctp-idata-72 \
                 sctp-idata-73 \
                 sctp-idata-74 \
                 sctp-idata-75 \
                 sctp-idata-76 \
                 sctp-idata-77 \
                 sctp-idata-78 \
                 sctp-idata-79 \
                 sctp-idata-80 \
                 sctp-idata-81 \
                 sctp-idata-82 \
                 sctp-idata-83 \
                 sctp-idata-84 \
                 sctp-idata-85 \
                 sctp-idata-86 \
                 sctp-idata-87 \
                 sctp-idata-88 \
                 sctp-idata-89 \
                 sctp-idata-90 \
                 sctp-idata-91 \
                 sctp-idata-92 \
                 sctp-idata-93 \
                 sctp-idata-94 \
                 sctp-idata-95 \
                 sctp-idata-96 \
                 sctp-idata-97 \
                 sctp-idata-98 \
                 sctp-idata-99 \
                 sctp-idata-100 \
                 sctp-idata-101 \
                 sctp-idata-102 \
                 sctp-idata-103 \
                 sctp-idata-104 \
                 sctp-idata-105 \
                 sctp-idata-106 \
                 sctp-idata-107 \
                 sctp-idata-108 \
                 sctp-idata-109 \
                 sctp-idata-110 \
                 sctp-idata-111 \
                 sctp-idata-112 \
                 sctp-idata-113 \
                 sctp-idata-114 \
                 sctp-idata-115 \
                 sctp-idata-116 \
                 sctp-idata-117 )

set rootdir = `/usr/bin/dirname $0`
set passed = 0
set failed = 0
set run = 0
set skipped = 0
set first = 1

printf "Name                                        Verdict\n"
printf "===================================================\n"
foreach testcase ($testcases)
  printf "%-40.40s " $testcase
  if ($first == 0) then
    if ($delay != 0) then
      printf "\033[33m%10s\033[0m" "WAITING"
      sleep $delay
      printf "\b\b\b\b\b\b\b\b\b\b"
    endif
  else
    set first = 0
  endif
  printf "\033[33m%10s\033[0m" "RUNNING"
  if (-f ${rootdir}/${testcase}.pkt) then
    $packetdrill --tolerance_usecs=75000 ${rootdir}/${testcase}.pkt >& /dev/null
    set result = $status
    set found = 1
  else
    set found = 0
  endif
  printf "\b\b\b\b\b\b\b\b\b\b"
  if ($found == 1) then
    if ($result == 0) then
      @ passed++
      printf "\033[32m%10s\033[0m\n" "PASSED"
    else
      @ failed++
      printf "\033[31m%10s\033[0m\n" "FAILED"
    endif
    @ run++
  else
    printf "\033[34m%10s\033[0m\n" "SKIPPED"
    @ skipped++
  endif
end
printf "===================================================\n"
printf "Summary: Number of tests run:     %3u\n" $run
printf "         Number of tests passed:  %3u\n" $passed
printf "         Number of tests failed:  %3u\n" $failed
printf "         Number of tests skipped: %3u\n" $skipped
